# Database
spring.datasource.url=jdbc:mysql://localhost:3306/connectsphere_db
spring.datasource.username=root
spring.datasource.password=Eipw1376?
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=connectsphere-super-secret-key-2026-make-this-very-long-for-security
app.jwt.expiry-ms=86400000

# Port
server.port=8081

logging.level.org.springframework.security=DEBUG
